version: '3'

services:
    app:
        restart: always
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                APP_ENV: local
        volumes:
            - .:/usr/share/nginx/html
        container_name: eccomerce_app
        depends_on:
            - database
        ports:
            - "9000:80"
        expose:
            - "80"

    # ----- MySQL Database ----- #
    database:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: eccomerce_db
            MYSQL_USER: eccomerce_user
            MYSQL_PASSWORD: 333kads8dfdsjf4
            MYSQL_ROOT_PASSWORD: 333kads8dfdsjf4
        volumes:
            - ./mysql-data:/var/lib/mysql/
        container_name: eccomerce_database

    # ----- Database UI manager. ----- #
    dbadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=database
            - PMA_PORT=3306
        ports:
            - 8080:80
        volumes:
            - /sessions
        links:
            - database
        depends_on:
            - database

    # ----- Redis Instance. ----- #
    redis:
        image: redis:alpine
        command: redis-server --requirepass 333kads8dfdsjf4
        volumes:
            - ./redis_backup:/data
        container_name: eccomerce_redis
